apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: skelly-saas
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.frontend.port | default 3000 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: frontend
