apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: skelly-saas
automountServiceAccountToken: false
