services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Api\:
        resource: '../../src/Api/'
        exclude:
            - '../../src/Api/ApiKernel.php'

    App\Infrastructure\:
        resource: '../../src/Infrastructure/'

    App\Domain\:
        resource: '../../src/Domain/'

    App\Infrastructure\Health\RedisConnectionInterface:
        class: App\Infrastructure\Health\PhpRedisConnection
        arguments:
            $redisUrl: '%env(REDIS_URL)%'
        tags:
            - { name: kernel.reset, method: reset }

    App\Infrastructure\Health\HealthChecker:
        arguments:
            $messengerTransportDsn: '%env(MESSENGER_TRANSPORT_DSN)%'

    App\Infrastructure\Health\HealthCheckerInterface:
        alias: App\Infrastructure\Health\HealthChecker
