apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pgbouncer
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/part-of: skelly-saas
spec:
  type: ClusterIP
  ports:
    - name: pgbouncer
      port: 6432
      targetPort: pgbouncer
      protocol: TCP
  selector:
    app.kubernetes.io/name: pgbouncer
