apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-workers
  labels:
    app.kubernetes.io/name: workers
    app.kubernetes.io/part-of: skelly-saas
automountServiceAccountToken: false
